- id: s3_backend_key
  name: Terrafrom s3 backend key paths
  description: Enforce all terraform s3 backend key paths match folder structure.
  entry: s3_backend_key.rb
  language: script
  files: (\.tf)$
  exclude: \.terraform\/.*$

- id: tf_provider_lock
  name: Add Terraform provider dependency lock file
  description: Add MacOS and Linux provider hashes to dependency lock file
  entry: tf_providers_lock.sh
  always_run: true
  language: script
  pass_filenames: false

- id: tf_version_check
  name: Terraform version and backend check
  description: Enforce terraform version matches .tool-versions and s3 backends use use_lockfile instead of dynamodb_table
  entry: tf_version_check.sh
  always_run: true
  language: script
  pass_filenames: false
