- id: s3_backend_key
  name: Terrafrom s3 backend key paths
  description: Enforce all terraform s3 backend key paths match folder structure.
  entry: s3_backend_key.rb
  language: script
  files: (\.tf)$
  exclude: \.terraform\/.*$

- id: bq_view_update
  name: Check for Big Query view updates
  description: When Big Query view sql files are updated ensure tf changes exist too so Alantis will plan correctly
  entry: bq_view_update.sh
  language: script
  pass_filenames: false